// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTdbUZet1bqBlubud5T0Y2c2yt8XAICZo',
    appId: '1:78349811898:web:40d89a7cb74c548d0c8283',
    messagingSenderId: '78349811898',
    projectId: 'wari-can-83f33',
    authDomain: 'wari-can-83f33.firebaseapp.com',
    databaseURL: 'https://wari-can-83f33-default-rtdb.firebaseio.com',
    storageBucket: 'wari-can-83f33.firebasestorage.app',
    measurementId: 'G-JZFK3MQB6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADjmQk9nKqUOJkQXLt1SnVv3OZAqtdq5M',
    appId: '1:78349811898:android:50a46bbf14f9a7500c8283',
    messagingSenderId: '78349811898',
    projectId: 'wari-can-83f33',
    databaseURL: 'https://wari-can-83f33-default-rtdb.firebaseio.com',
    storageBucket: 'wari-can-83f33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkNo6XB_W1nxh1Jup_DXR0UQ4madfi5yo',
    appId: '1:78349811898:ios:c1bdf82e605b9c4d0c8283',
    messagingSenderId: '78349811898',
    projectId: 'wari-can-83f33',
    databaseURL: 'https://wari-can-83f33-default-rtdb.firebaseio.com',
    storageBucket: 'wari-can-83f33.firebasestorage.app',
    iosBundleId: 'com.example.wariCan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkNo6XB_W1nxh1Jup_DXR0UQ4madfi5yo',
    appId: '1:78349811898:ios:c1bdf82e605b9c4d0c8283',
    messagingSenderId: '78349811898',
    projectId: 'wari-can-83f33',
    databaseURL: 'https://wari-can-83f33-default-rtdb.firebaseio.com',
    storageBucket: 'wari-can-83f33.firebasestorage.app',
    iosBundleId: 'com.example.wariCan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTdbUZet1bqBlubud5T0Y2c2yt8XAICZo',
    appId: '1:78349811898:web:3cc6b6871fa4e9790c8283',
    messagingSenderId: '78349811898',
    projectId: 'wari-can-83f33',
    authDomain: 'wari-can-83f33.firebaseapp.com',
    databaseURL: 'https://wari-can-83f33-default-rtdb.firebaseio.com',
    storageBucket: 'wari-can-83f33.firebasestorage.app',
    measurementId: 'G-FBJ6JRXMLT',
  );

}